### ISSUE TITLE
Question about allocating

### ISSUE THREAD

**Issue by Houndoom96** [rnavarroperez/nn-scattering-fit#2]
The observables subroutine has a lot of allocatable arrays. We will be calling the observables subroutine multiple times, so these arrays will be allocated every time we call the subroutine. In previous programs I have used  `if(allocated(x)) deallocate(x)`. Will this be necessary to do for every allocatable array? Or those calling the `allocate(x)` again clears the data in the array?

**Comment by rnavarroperez** [comment]
Actually, One thing that we didn't cover in PHYS580 is that allocatable arrays that are passed as arguments with `intent(out)` are automatically deallocated every time the program enters that subroutine. 

In fact, as you can see in the `all_phaseshifts` subroutine the `d_phases` argument is declared as 

``` fortran
real(dp), allocatable, intent(out) :: d_phases(:, :, :)
```
And then when the subroutine starts it goes directly into allocating with
``` fortran
allocate(d_phases(1:n_params, 1:n_waves, 1:j_max))
```

Similarly, variables that are ***declared inside*** the subroutine like
``` fortran
real(dp), allocatable, dimension(:) :: d_alfa_1, d_alfa_2
```
Don't need to be deallocated at the beginning of the subroutine because you know they are not allocated because you just created them. One caveat, if later within that same subroutine you want to change the size of the array you will need to deallocate and reallocate.

What if an allocatable argument is declared with `intent(in)`? Well, since the intent is `in` you shouldn't be changing it's size anyway.

What if an allocatable argument is declared with `intent(inout)`? That's where you need to be careful to make sure that you're not allocating an array that is already allocated. That's where the  `if(allocated(x)) deallocate(x)` makes the most sense.
