### ISSUE TITLE
warning on chiral potential branch when compiling

### ISSUE THREAD

**Issue by kyputnam** [rnavarroperez/nn-scattering-fit#26]
When compiling the chiral_potential branch I get the warning message:

> chiral_potential.f90:95:63:
> 
>    95 | subroutine chiral_potential_operator(parameters, r, v_nn, dv_nn)
>       |                                                                                                1
> Warning: Dummy argument ‘dv_nn’ at (1) was declared INTENT(OUT) but was not set [-Wunused-dummy-argument]
> gfortran -O3 -fopenmp -fcheck=all -Wall -pedantic -fimplicit-none -std=f2008 -fwhole-file -march=native -c av18.f90

This seems to be directly related to what is currently line 100:

`    real(dp), allocatable, intent(out) :: dv_nn(:, :) !< derivatives of v_nn with respect to the parameters in parameters`

I did not write this part of the code so I don't want to mess with it too much. @rnavarroperez, could you take a look?

**Comment by rnavarroperez** [comment]
I was just writing you about it.

I looked into the changes you had made in `chiral_potential_operator` and the sum of long range plus short range is all correct.

I also just took a quick look into the changes you just pushed and those also look good.

There is one thing that is missing though that we forgot about yesterday. That is, the derivatives of `v_nn` the need to be put into the `dv_nn` array in the `chiral_potential_operator` subroutine, which is what is causing the warning when compiling.

In principle the derivatives of `v_nn` are just the derivatives that where already calculated in `d_v_short`. But as you know from lines 111 to 129 of `chiral_potential.f90` the arrays `v_nn` and `v_short` have the operators in a different order.  In the spirit of simplicity I think it will be better to make changes so that both `long_range_potentials` and `short_range_potentials` use the same order as `av18_operator`.  For that you'll need to make a few changes

## Changes to `long_range_potentials`

You should change 

```fortran
subroutine long_range_potentials(r, R_L, a_L, v_c, v_tau, v_sigma, v_sigma_tau, v_t, v_t_tau)
``` 
for 
```fortran
subroutine long_range_potentials(r, R_L, a_L, v_long)
``` 
This change needs to happen both in `long_range_chiral_potentials.f90` where the subroutine is defined and everywhere else where the subroutine is called (e.g. in `chiral_potential_operator` and I believe in `read_write`)

`v_long` is an array of size 19. Elements 1 through 6 should contain what is currently in `v_c`, `v_tau`, `v_sigma`, etc. Elements 7 through 13 should be zero, element 14 should be what is currently in `v_sigma_T`, element 15 should be what is currently in `v_t_T`, and elements 16 to 19 should be zero.

## Changes to `short_range_potentials`

Here you need to change `n_potentials` to 19 and then change the order in which the potentials are stored into `v_short` to match the order from `av18`. Elements 1 through 8 keep the same order, element 9 should contain `v_q` (currently in element 10), elements 10, 12, and 14 should now be empty (because there's no l2_tau, l2_sigma_tau or ls2_tau terms in the definitions of the appendix),  element 11 stays the same,  element 13 should now contain `v_bb` (currently in element 9), and similar swaps for elements 15 through 19.

Then don't forget to make the same order change to `d_v_short`

## Changes to `chiral_potential_operator`

Here is where those changes will pay off. Now, after the calls to `long_range_potentials` and `short_range_potentials` you can simply do
``` fortran
v_nn = v_long + v_short
allocate(dv_nn, source=d_v_short)
```
The first line will add the `v_long` and `v_short` arrays elementwise and store that in `v_nn`, the second line will allocate the derivatives array to have the same size and contents as `d_v_short`, which is what we want.

**Comment by rnavarroperez** [comment]
Also, just took a look at your `namelist` file.

It looks mostly correct. There is just one small issue with the order of the parameters. Although I did say that namelist files are pretty flexible, the order in which the elements of an array in a namelist file are read is fixed. That order is from left to right and top to bottom. 

The way the file is currently written will store `2.936041`  (which corresponds to `C_s`) in the first element, `-0.08647128` (which corresponds to `D_10`) in the second element, `-0.4933897` (which corresponds to `C_T`) in the third element and so on. Even though the comments help us humans to know which number corresponds to which LEC fortran will just ignore the comments when reading the file.

So for now lets just put the parameters in a single column with the same order as the order used for the default parameters in `chiral_potential.f90`. We can come up with a nicer way to write them that maintains the order later.

**Comment by kyputnam** [comment]
I made the changes that we discussed and just pushed them. The warning is no longer showing up. Thanks for your help!
