### ISSUE TITLE
Trouble running 125 MeV model a

### ISSUE THREAD

**Issue by kyputnam** [rnavarroperez/nn-scattering-fit#28]
I added a namelist file for model a at 125 MeV (a with no tilde), [a72ab81](https://github.com/rnavarroperez/nn-scattering-fit/commit/a72ab815101bdca357442776f2997b11f58c4c93), and the program is returning the following error when I try to run it:

> Setting up potential as specified in: chiral_potential_a_125.namelist
>  
> STOP Error reading potential_parameters namelist

I'm having trouble seeing what the error is with the potential parameters. As far as I can tell the namelist file is exactly the same as the other namelists files I have that do run, only with different parameters.

**Comment by rnavarroperez** [comment]
Hi @kyputnam 

There were a few typos in the new namelist file that were causing the error when reading. For some reason some of the negative parameters had a long dash `−` instead of a minus sign `-`

Also a new line is needed at the end of every namelist file (that's just the way namelist files work) which was missing at the end of the `adjust_parameters` namelist.

The code runs for me now
